version: "3.8"

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8880:8080"

  anfis:
    container_name: anfis
    image: anfis:latest
    restart: unless-stopped
    ports:
      - "8808:8888"
